//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_Mall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Fdbk_Id { get; set; }
        public string User_Name { get; set; }
        public string Message { get; set; }
    }
}
