//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_Mall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int Shop_Id { get; set; }
        public Nullable<int> Shop_Number { get; set; }
        public string Shop_Owner { get; set; }
        public string Shop_Type { get; set; }
        public string Shop_Products { get; set; }
    }
}
